In [ ]:
#pip install pandas mysql-connector-python

In [2]:
import pandas as pd

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv(r'C:\Users\Michel Diego\Downloads\Database_LeevinGL21052024.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Michel Diego\\Downloads\\Database_LeevinGL21052024.csv'

In [106]:
df.columns = df.iloc[0]
df = df[2:]
df

,Company,ID,Property,Landlord,Group,Address,City,Zone,Eircode,Room info,Included Bills,# of bathrooms,#REF!,#REF!,Merge,Gender,Vacancy ID,Group Room,Type Room,Property Type,Vacancy Status,Vacancy Status,Current Price,Base Price (2023),Proj. 2024,Proj. 2025,Proj. 2026,Renovação Aplicada,PROJECTION,Proj. month,Deposit Amount,Booking Code,Customer,Entry Date,Expired Date,Contract duration,Total duration of contract,Rent day,Year,Month,Last Notice Date,Last Open Date,Vacancy Abandonement,Status of Payment,Status deposito,Note,8.0,Entry Month,Entry Year
2,Leevin,Erin,North Great 43 - School,Neil,NaN,43 North Great George's Street,Dublin,D01,D01 K023,NaN,NaN,NaN,1,NaN,Leevin,NaN,NaN,School,School,Home (entire house),Close,1,"17,083.33","17,083.33","17,425.00","17,774.00","18,129.00",NaN,NaN,NaN,"17,083.33",6414,Erin School - Lucas Finelli,01/06/2021,01/12/2024,12 meses,42 Months 19 Days,21,2024,12,NaN,NaN,NaN,Paid,DESCONTO,NaN,NaN,6,2021
3,Leevin,G1103,Gardiner Street Middle 24 - Apt 1,Neil,Gardiner Street,"24 Gardiner Street Middle, Apt 1",Dublin,D01,D01 E084,NaN,NaN,1 bathroom,7,5,Merge,NaN,GA24AP01B11,Room 1.1,Twin,Home (entire house),Close,4,"2,448.00","2,400.00","2,448.00","2,497.00","2,547.00",December Email ok,"2,448.00",9,"2,400.00",16160,Madhav Kalra,22/02/2024,21/06/2024,4 meses,4 Months,22,2024,6,NaN,NaN,NaN,NaN,NaN,criado novo booking Leevin - 7109,NaN,2,2024
4,Leevin,G1103,Gardiner Street Middle 24 - Apt 1,Neil,Gardiner Street,"24 Gardiner Street Middle, Apt 1",Dublin,D01,D01 E084,NaN,NaN,1 bathroom,7,5,Merge,NaN,GA24AP01B12,Room 1.2,Twin,Home (entire house),Close,1,0.00,0.00,0.00,0.00,0.00,December Email ok,NaN,9,0.00,16161,Herin Bipin Vora,22/10/2023,21/06/2024,4 meses,8 Months 3 Days,22,2024,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
5,Leevin,G1103,Gardiner Street Middle 24 - Apt 1,Neil,Gardiner Street,"24 Gardiner Street Middle, Apt 1",Dublin,D01,D01 E084,NaN,NaN,1 bathroom,7,2,Merge,NaN,GA24AP01B21,Room 2.1,Twin,Home (entire house),Close,1,0.00,0.00,0.00,0.00,0.00,December Email ok,NaN,9,0.00,16162,Vinayak Kantaram Hinge,22/10/2023,21/06/2024,4 meses,8 Months 3 Days,22,2024,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
6,Leevin,G1103,Gardiner Street Middle 24 - Apt 1,Neil,Gardiner Street,"24 Gardiner Street Middle, Apt 1",Dublin,D01,D01 E084,NaN,NaN,1 bathroom,7,2,Merge,NaN,GA24AP01B22,Room 2.2,Twin,Home (entire house),Close,1,0.00,0.00,0.00,0.00,0.00,NaN,NaN,9,0.00,16163,Pratik Arjun Gadkar,22/10/2023,21/06/2024,4 meses,8 Months 3 Days,22,2024,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.columns

Index(['Company', 'ID', 'Property', 'Landlord', 'Group', 'Address', 'City',
       'Zone', 'Eircode', 'Room info', 'Included Bills', '# of bathrooms',
       '#REF!', '#REF!.1', 'Merge', 'Gender', 'Vacancy ID', 'Group Room',
       'Type Room', 'Property Type', 'Vacancy Status', 'Vacancy Status.1',
       'Current_Price', 'Base Price (2023)', 'Proj. 2024', 'Proj. 2025',
       'Proj. 2026', 'Renovação Aplicada ', 'PROJECTION', 'Proj. month',
       'Deposit Amount', 'Booking Code', 'Customer', 'Entry Date',
       'Expired Date', 'Contract duration', 'Total duration of contract',
       'Rent day', 'Year', 'Month', 'Last Notice Date', 'Last Open Date',
       'Vacancy Abandonement', 'Func. Leevin', 'Status of Payment',
       'Status deposito', 'Note', '12', 'Entry Month', 'Entry Year'],
      dtype='object')

In [18]:
df = df.drop('Renovação Aplicada ', axis=1)
df

,Company,ID,Property,Landlord,Group,Address,City,Zone,Eircode,Room info,Included Bills,# of bathrooms,#REF!,#REF!.1,Merge,Gender,Vacancy ID,Group Room,Type Room,Property Type,Vacancy Status,Vacancy Status.1,Current_Price,Base Price (2023),Proj. 2024,Proj. 2025,Proj. 2026,PROJECTION,Proj. month,Deposit Amount,Booking Code,Customer,Entry Date,Expired Date,Contract duration,Total duration of contract,Rent day,Year,Month,Last Notice Date,Last Open Date,Vacancy Abandonement,Func. Leevin,Status of Payment,Status deposito,Note,12,Entry Month,Entry Year
0,Leevin,Cream,The Barley House - Factory,-,NaN,"Block A The Barley House, 90-97 Cork St, The L...",Dublin,D08,D08 N5PE,NaN,NaN,NaN,1.0,NaN,Leevin,NaN,TBH,Factory,Factory,Home,Return,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN,Paid,DESCONTO,NaN,NaN,NaN,NaN
1,Leevin,Erin,Erin,Neil,NaN,43 North Great George's Street,Dublin,D01,D01 K023,NaN,NaN,NaN,1.0,NaN,Leevin,NaN,NaN,School,School,Home (entire house),Close,1.0,17083.33,17083.33,17425.0,17774.0,18129.0,NaN,NaN,17083.33,6414,Erin School - Lucas Finelli,01/06/2021,01/12/2024,12 meses,42 Months 19 Days,21.0,2024,12,NaN,NaN,NaN,NaN,Paid,DESCONTO,NaN,NaN,6,2021
2,Leevin,G1103,Gardiner Street Middle 24 - Apt 1,Neil,Gardiner Street,"24 Gardiner Street Middle, Apt 1",Dublin,D01,D01 E084,NaN,NaN,1 bathroom,7.0,5.0,Merge,NaN,GA24AP01B11,Room 1.1,Twin,Home (entire house),Ending,4.0,612.00,2400.00,2448.0,2497.0,2547.0,2448,9,600.00,16160,Madhav Kalra,22/02/2024,21/06/2024,4 meses,4 Months,22.0,2024,6,NaN,NaN,NaN,NaN,NaN,NaN,criado novo booking Leevin - 7109,NaN,2,2024
3,Leevin,G1103,Gardiner Street Middle 24 - Apt 1,Neil,Gardiner Street,"24 Gardiner Street Middle, Apt 1",Dublin,D01,D01 E084,NaN,NaN,1 bathroom,7.0,5.0,Merge,NaN,GA24AP01B12,Room 1.2,Twin,Home (entire house),Ending,1.0,612.00,0.00,0.0,0.0,0.0,NaN,9,600.00,17449,Akshit Mistry,22/03/2024,21/06/2024,3 meses,3 Months 1 Days,22.0,2024,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2024
4,Leevin,G1103,Gardiner Street Middle 24 - Apt 1,Neil,Gardiner Street,"24 Gardiner Street Middle, Apt 1",Dublin,D01,D01 E084,NaN,NaN,1 bathroom,7.0,2.0,Merge,Male,GA24AP01B21,Room 2.1,Twin,Home (entire house),Notice,1.0,612.00,0.00,0.0,0.0,0.0,NaN,9,600.00,16162,Vinayak Kantaram Hinge,22/10/2023,21/06/2024,4 meses,8 Months 3 Days,22.0,2024,6,45466.0,45466.0,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
import pandas as pd
from sqlalchemy import create_engine

# Read CSV file into a DataFrame
#df = pd.read_csv(r'C:\Users\Michel Diego\Downloads\Database_LeevinGL19052024.csv')

# Define your MySQL server connection details
username = 'root'
password = 'Md502386'
hostname = 'localhost'  # Or your MySQL server IP address
port = '3306'  # Default MySQL port is 3306
database = 'dataleevingl'

# Create a connection string
connection_string = f'mysql+mysqlconnector://{username}:{password}@{hostname}:{port}/{database}'

# Establish a connection to the MySQL database
engine = create_engine(connection_string)

# Write DataFrame to MySQL database
df.to_sql(name='database_leevingl21052024', con=engine, if_exists='replace', index=False)

# Dispose the engine to release the connection resources
engine.dispose()